### ISSUE TITLE
The test for verticalAlignmentTop often fails in CI.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#370]
### Describe the bug

This fix clearly does not make any changes to the generator, yet the CI fails.
https://github.com/pdfme/pdfme/actions/runs/7231153655/job/19704026199

### To Reproduce

It happens regularly on PRs.

### Expected behavior

Improving performance to address this issue would be ideal, but other potential solutions include:
- Modifying the template for verticalAlignmentTop
- Changing the threshold for test failure

### Your Environment

```markdown
- @pdfme/generator
- pdfme version: latest
- Operating system: CI
- Node.js version or Browser name & version: Node v20
```

### Your Error Log

```shell
none
```

**Comment by peteward** [comment]
I think it's because there are 3 different fonts that might be quite large to load.

The fonts were chosen because of their design values - they have very different ascent and descent values. I think we should keep them.

the times for the different fonts are similar for those with these fonts, so we would have to change lots of files:

```
      dynamicFontSizeHorizontal time: 0,674701000
      dynamicFontSizeVertical time: 0,320391375
      verticalAlignmentTop time: 0,724541833
      verticalAlignmentMiddle time: 0,687650458
      verticalAlignmentBottom time: 0,692919459
      test time: 0,121354459
      z97mmx210mm time: 0,88564167
      canvasPdf time: 0,100879083
      background time: 0,168999375
      rotation time: 0,182609833
```

I think we should increase the time, I can look at doing this later.
