### ISSUE TITLE
Feature Request - Ability to generate tables on a pdf template

### ISSUE THREAD

**Issue by mcornielje090404** [pdfme/pdfme#473]
### Is your feature request related to a problem? Please describe.

I am unable to generate tables within a pdf template. This is very limiting as I need to be able to generate these PDF's based on a previously made template and just slap the dynamic data on top.

### Describe the solution you'd like

Currently it requires an object of

```js
{
  width: number;
  height: number;
  padding: [number, number, number, number]
}
```

A possible solution could be to append 

```js
{
  file?: ArrayBuffer | UInt8Array etc.
}
```

to the basePdf object requiring padding, width, and height (ideally the width and height could be automatically determined if a file is added?).

I was wondering if there was a reason this wasn't previously implemented as it seems like a core aspect of the package to be able to insert templates and add dynamic data to them.

### Describe alternatives you've considered

An alternative could be to put the width, height, and padding of a pdf into an options object within the generate function/designer function etc.

**Comment by hand-dot** [comment]
At this point, this is not a bug but a specification. (We determined that it would be difficult to apply page breaks to existing PDFs.)
Currently, you can render tables by specifying the size and padding for basePdf as follows:

```
"basePdf": { "width": 210, "height": 297, "padding": [10,10,10,10] }
```

However, due to frequent user feedback, we may modify it so that tables can be adapted to any basePdf.

Related issues:
* https://github.com/pdfme/pdfme/issues/473
* https://github.com/pdfme/pdfme/issues/479
* https://github.com/pdfme/pdfme/issues/482
* https://github.com/pdfme/pdfme/issues/486

**Comment by hand-dot** [comment]
We will consolidate this issue and address it here: https://github.com/pdfme/pdfme/issues/486

We haven't yet decided on specific specifications, so please feel free to post any opinions or suggestions you may have.
