### ISSUE TITLE
Can't add tables with Dynamic Data to a Base PDF

### ISSUE THREAD

**Issue by grahamorrell** [pdfme/pdfme#479]
### Describe the bug

I would like to add a table containing Dynamic Data to a Base PDF of my choosing.  This doesn't seem to work or be supported.

### To Reproduce

On the playground : https://playground.pdfme.com/ choose the "Invoice" preset to show the Dynamic Table example.  Now from "Change BasePDF" choose a PDF file.  All of the elements appear in place on top of the BasePDF *except* the Dynamic table.

### Expected behavior

Dynamic Tables should be able to be added on top of Base PDFs

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):  ^4.0.0
- pdfme version:  ^4.0.0
- Operating system:  Windows  
- Node.js version or Browser name & version:  20.9.0, Edge 124
```

### Your Error Log

```shell
No error log
```

**Comment by mschuch** [comment]
I have the same issue, when I change the base PDF.
I use Version 4.0.1

**Comment by grahamorrell** [comment]
@hand-dot is this something that is on the radar to look at?

**Comment by hand-dot** [comment]
At this point, this is not a bug but a specification. (We determined that it would be difficult to apply page breaks to existing PDFs.)
Currently, you can render tables by specifying the size and padding for basePdf as follows:

```
"basePdf": { "width": 210, "height": 297, "padding": [10,10,10,10] }
```

However, due to frequent user feedback, we may modify it so that tables can be adapted to any basePdf.

Related issues:
* https://github.com/pdfme/pdfme/issues/473
* https://github.com/pdfme/pdfme/issues/479
* https://github.com/pdfme/pdfme/issues/482
* https://github.com/pdfme/pdfme/issues/486

**Comment by hand-dot** [comment]
We will consolidate this issue and address it here: https://github.com/pdfme/pdfme/issues/486

We haven't yet decided on specific specifications, so please feel free to post any opinions or suggestions you may have.
