### ISSUE TITLE
Changing a field name so that it duplicates another will remove one of the fields

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#529]
### Describe the bug

If you change the name of a field to that of an existing one then one of the fields will be removed as soon as you select off of the schema.

### To Reproduce

* Add a schema `field1`
* Add another schema and rename it to `field1` 
* When you lose focus on that schema there will only be 1 field remaining

### Expected behavior

Now that we have code that prevents field updates if they are invalid, we should be able to apply a custom validation rule to the field name form element which will mark it as an error if it equals any other field names.  This will prevent it being saved, so no fields will be accidentally 'lost'.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): UI
- pdfme version: latest main
```

### Your Error Log

```shell
-
```

**Comment by hand-dot** [comment]
@peteward 
I can't reproduce...
Could you update your Chrome?

Chrome: Version 127.0.6533.89 (Official Build) (arm64)

![CleanShot 2024-07-31 at 18 19 01](https://github.com/user-attachments/assets/ba1b0643-c534-493d-a7d1-631d3fcf4568)

**Comment by peteward** [comment]
Hmm interesting...

Version 127.0.6533.89 (Official Build) (arm64)


https://github.com/user-attachments/assets/ddc7a43b-c747-4e64-94b9-75fbd66c0791

**Comment by hand-dot** [comment]
Hmm.
Does it also occur in an incognito browser on the [playground](https://playground.pdfme.com)?
There's a possibility that Chrome extensions might be involved.

If it does occur in an incognito browser, could it be due to this fix?
https://github.com/pdfme/pdfme/pull/506/files

This might be a bit of a leap, but I'd like to make it possible to automatically update the PDFME_VERSION below, in order to check which version the current playground is running on.
https://github.com/pdfme/pdfme/blob/main/packages/common/src/constants.ts#L2

**Comment by peteward** [comment]
It seems to be due to the Lastpass chrome extension.

I think the improvement to validation is still worth exploring, but I will also try `data-lpignore="true"` to see if this prevents it.

**Comment by peteward** [comment]
implemented
