### ISSUE TITLE
Generated file size bigger than expected

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#53]
ref https://github.com/pdfme/pdfme/discussions/51

**Comment by sushi2all** [comment]
Any news here? I'm trying to use pdfme to generate labels to print, but the file size is pretty huge (180+KB for the sample label below) and label printers are struggling to manage it.

![image](https://github.com/user-attachments/assets/eab0058e-9d83-4e5d-be34-f73df41a9966)

**Comment by hand-dot** [comment]
Hi @sushi2all 

Could you list all the arguments passed to the generate function?  
Could the issue of increasing file size be related to the font or the basePdf?

**Comment by sushi2all** [comment]
I noticed the base pdf data saved in the template was very long, and I wondered why since it was a white rectangle. 

To generate the blank base pdf I took a screenshot of a blank page and sized it to what I wanted and then converted it to pdf. 

I realized that passing through an image might increase the size so I tried exporting to pdf a white rectangle from figma and the size turned down to 4K. So that was it.

Not an issue anymore in my case.

Thanks.
