### ISSUE TITLE
How to get current page number

### ISSUE THREAD

**Issue by ajitRajawat** [pdfme/pdfme#61]
I am adding fields manually and how to get the current focused page number in a multi-page pdf.
Need page number to add field on that particular index in schema and sample data.

So can anyone suggest me same?

**Comment by hand-dot** [comment]
No, we don't need page number, because the schema is an array, the schema's elements represent each pdf page,

![Untitled-2022-05-23-1557 excalidraw](https://user-images.githubusercontent.com/24843808/169762756-f66c8f6e-88fb-4e34-a6b9-2f3bac87fc50.png)

**Comment by ajaralampidis** [comment]
@hand-dot,

This would be really usefull here: https://pdfme.com/docs/getting-started#template .
I had some errors with the Form because I was not aware that schemas expect one object per pdf page. 
I was using inputs only in the first page so my schema's array contained only one object (while the pdf has two pages):

```
"schemas": 
    [
      { input1: { ... }, input2: { ... }, ... }
    ]
```

pdfme will render the pdf and the inputs but the `generate` function will throw an error saying it can't find the inputs:

```
index.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'input1')
    at index.js:2:1
    at Generator.next (<anonymous>)
    at o (index.js:2:1)
```

This is simply fixed by adding an object per page in the schema's so I am not sure if this is truly a bug but I guess adding this to the docs would be useful.

Btw: Thanks for the project !

**Comment by erikmaday** [comment]
@ajitRajawat 

I also need the current page. The best I've come up with is a hacky way through observing the DOM. This is implemented in Vue, but should be fairly transferable to any JS framework or Vanilla JS.

```
setupObserver(): void {
  const container = document.getElementById('pdf-container');
  
  if (!container) return;
  
  const config = { childList: true, subtree: true };

  this.observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.addedNodes.length > 0) {
        this.readPageValues();
      }
    });
  });

  this.observer.observe(container, config);
}

readPageValues(): void {
  document.querySelectorAll('div').forEach((div) => {
    const isFlexDisplay = getComputedStyle(div).display === 'flex';
    if (!isFlexDisplay) {
      return;
    }
    const strong = div.querySelector('strong');
    if (!strong) {
      return;    
    }
    const content = strong.textContent || '';
    const regex = /^\d+\/\d+$/; // Regular expression to match the #/# format
    if (!regex.test(content)) {
      return;
    }
    const split = content.split('/');
    this.currentPage = parseInt(split[0], 10)
    this.totalPages = parseInt(split[1], 10)
  });
}
```
