### ISSUE TITLE
QR code with Japanese characters

### ISSUE THREAD

**Issue by leduclinh7141** [pdfme/pdfme#63]
[4aa0b7ff-16fe-44c1-bfe6-f3c139b1e36e.pdf](https://github.com/pdfme/pdfme/files/8545212/4aa0b7ff-16fe-44c1-bfe6-f3c139b1e36e.pdf)
Hi, I tried the playground app and changed the owner field "https://pdfme.com/" to "1907/KMB13600Y1/1116624693/12345/19040201/勝海/住友建機㈱/SH135-7（2850ｋ）".
After I clicked the "Generate PDF" button, the QR code could not be readable, or maybe its content was empty.

Do I miss something, or does it need some settings to show a QR code with Japanese characters?

Thank you for your excellent work!

**Comment by hand-dot** [comment]
Hi,  @leduclinh7141 ! 
Thank you for the bug report.

This problem is caused by the character code of the QR code.
Some QR code reader doesn't read Japanese as Shift_JIS.
Therefore, the result is depends on QR code reader.

I used "QRQR - QR Code® Reader" app, all the characters were read correctly.
https://play.google.com/store/apps/details?id=com.arara.q&hl=en&gl=US

ref https://github.com/hand-dot/labelmake/pull/57#issuecomment-990683287

If you have any question, please feel free to ask.

**Comment by hand-dot** [comment]
@leduclinh7141 
I labeled the answer because I did not receive a reply.
If there are no replies at this point, it will be closed after 30 days.
If you have any questions, please comment.
